/**
 * Client
 * AvatarYug Client side API
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package Avataryug.Client.Model;

import io.swagger.annotations.*;
import com.google.gson.annotations.SerializedName;

@ApiModel(description = "")
public class ConsumeInstanceRequest {
  
  @SerializedName("UserID")
  private String userID = null;
  @SerializedName("ID")
  private String ID = null;
  @SerializedName("InstanceCount")
  private Integer instanceCount = null;

  /**
   * Unique instance identifier of the item to be consumed.
   **/
  @ApiModelProperty(value = "Unique instance identifier of the item to be consumed.")
  public String getUserID() {
    return userID;
  }
  public void setUserID(String userID) {
    this.userID = userID;
  }

  /**
   * Number of uses to consume from the item.
   **/
  @ApiModelProperty(value = "Number of uses to consume from the item.")
  public String getID() {
    return ID;
  }
  public void setID(String ID) {
    this.ID = ID;
  }

  /**
   **/
  @ApiModelProperty(required = true, value = "")
  public Integer getInstanceCount() {
    return instanceCount;
  }
  public void setInstanceCount(Integer instanceCount) {
    this.instanceCount = instanceCount;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ConsumeInstanceRequest consumeInstanceRequest = (ConsumeInstanceRequest) o;
    return (this.userID == null ? consumeInstanceRequest.userID == null : this.userID.equals(consumeInstanceRequest.userID)) &&
        (this.ID == null ? consumeInstanceRequest.ID == null : this.ID.equals(consumeInstanceRequest.ID)) &&
        (this.instanceCount == null ? consumeInstanceRequest.instanceCount == null : this.instanceCount.equals(consumeInstanceRequest.instanceCount));
  }

  @Override
  public int hashCode() {
    int result = 17;
    result = 31 * result + (this.userID == null ? 0: this.userID.hashCode());
    result = 31 * result + (this.ID == null ? 0: this.ID.hashCode());
    result = 31 * result + (this.instanceCount == null ? 0: this.instanceCount.hashCode());
    return result;
  }

  @Override
  public String toString()  {
    StringBuilder sb = new StringBuilder();
    sb.append("class ConsumeInstanceRequest {\n");
    
    sb.append("  userID: ").append(userID).append("\n");
    sb.append("  ID: ").append(ID).append("\n");
    sb.append("  instanceCount: ").append(instanceCount).append("\n");
    sb.append("}\n");
    return sb.toString();
  }
}
