/**
 * Client
 * AvatarYug Client side API
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package Avataryug.Client.Model;

import io.swagger.annotations.*;
import com.google.gson.annotations.SerializedName;

@ApiModel(description = "")
public class GetAdPlacementByIDResultData {
  
  @SerializedName("PlacementName")
  private String placementName = null;
  @SerializedName("Platform")
  private String platform = null;
  @SerializedName("AdFormat")
  private String adFormat = null;
  @SerializedName("AdUnit")
  private String adUnit = null;
  @SerializedName("Rewards")
  private String rewards = null;
  @SerializedName("AdLimits")
  private String adLimits = null;
  @SerializedName("Status")
  private Integer status = null;
  @SerializedName("ID")
  private String ID = null;

  /**
   **/
  @ApiModelProperty(value = "")
  public String getPlacementName() {
    return placementName;
  }
  public void setPlacementName(String placementName) {
    this.placementName = placementName;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public String getPlatform() {
    return platform;
  }
  public void setPlatform(String platform) {
    this.platform = platform;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public String getAdFormat() {
    return adFormat;
  }
  public void setAdFormat(String adFormat) {
    this.adFormat = adFormat;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public String getAdUnit() {
    return adUnit;
  }
  public void setAdUnit(String adUnit) {
    this.adUnit = adUnit;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public String getRewards() {
    return rewards;
  }
  public void setRewards(String rewards) {
    this.rewards = rewards;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public String getAdLimits() {
    return adLimits;
  }
  public void setAdLimits(String adLimits) {
    this.adLimits = adLimits;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public Integer getStatus() {
    return status;
  }
  public void setStatus(Integer status) {
    this.status = status;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public String getID() {
    return ID;
  }
  public void setID(String ID) {
    this.ID = ID;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    GetAdPlacementByIDResultData getAdPlacementByIDResultData = (GetAdPlacementByIDResultData) o;
    return (this.placementName == null ? getAdPlacementByIDResultData.placementName == null : this.placementName.equals(getAdPlacementByIDResultData.placementName)) &&
        (this.platform == null ? getAdPlacementByIDResultData.platform == null : this.platform.equals(getAdPlacementByIDResultData.platform)) &&
        (this.adFormat == null ? getAdPlacementByIDResultData.adFormat == null : this.adFormat.equals(getAdPlacementByIDResultData.adFormat)) &&
        (this.adUnit == null ? getAdPlacementByIDResultData.adUnit == null : this.adUnit.equals(getAdPlacementByIDResultData.adUnit)) &&
        (this.rewards == null ? getAdPlacementByIDResultData.rewards == null : this.rewards.equals(getAdPlacementByIDResultData.rewards)) &&
        (this.adLimits == null ? getAdPlacementByIDResultData.adLimits == null : this.adLimits.equals(getAdPlacementByIDResultData.adLimits)) &&
        (this.status == null ? getAdPlacementByIDResultData.status == null : this.status.equals(getAdPlacementByIDResultData.status)) &&
        (this.ID == null ? getAdPlacementByIDResultData.ID == null : this.ID.equals(getAdPlacementByIDResultData.ID));
  }

  @Override
  public int hashCode() {
    int result = 17;
    result = 31 * result + (this.placementName == null ? 0: this.placementName.hashCode());
    result = 31 * result + (this.platform == null ? 0: this.platform.hashCode());
    result = 31 * result + (this.adFormat == null ? 0: this.adFormat.hashCode());
    result = 31 * result + (this.adUnit == null ? 0: this.adUnit.hashCode());
    result = 31 * result + (this.rewards == null ? 0: this.rewards.hashCode());
    result = 31 * result + (this.adLimits == null ? 0: this.adLimits.hashCode());
    result = 31 * result + (this.status == null ? 0: this.status.hashCode());
    result = 31 * result + (this.ID == null ? 0: this.ID.hashCode());
    return result;
  }

  @Override
  public String toString()  {
    StringBuilder sb = new StringBuilder();
    sb.append("class GetAdPlacementByIDResultData {\n");
    
    sb.append("  placementName: ").append(placementName).append("\n");
    sb.append("  platform: ").append(platform).append("\n");
    sb.append("  adFormat: ").append(adFormat).append("\n");
    sb.append("  adUnit: ").append(adUnit).append("\n");
    sb.append("  rewards: ").append(rewards).append("\n");
    sb.append("  adLimits: ").append(adLimits).append("\n");
    sb.append("  status: ").append(status).append("\n");
    sb.append("  ID: ").append(ID).append("\n");
    sb.append("}\n");
    return sb.toString();
  }
}
