/**
 * Client
 * AvatarYug Client side API
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package Avataryug.Client.Model;

import io.swagger.annotations.*;
import com.google.gson.annotations.SerializedName;

@ApiModel(description = "")
public class GetAvatarPresetByIDRequestData {
  
  @SerializedName("DisplayName")
  private String displayName = null;
  @SerializedName("Description")
  private String description = null;
  @SerializedName("VirtualCurrency")
  private String virtualCurrency = null;
  @SerializedName("RealCurrency")
  private Integer realCurrency = null;
  @SerializedName("CustomMetaData")
  private String customMetaData = null;
  @SerializedName("ImageArtifacts")
  private String imageArtifacts = null;

  @SerializedName("MeshArtifacts")
  private String meshArtifacts = null;
  @SerializedName("BlendshapeKeys")
  private String blendshapeKeys = null;
  @SerializedName("Tags")
  private String tags = null;
  @SerializedName("Props")
  private String props = null;
  @SerializedName("Gender")
  private Integer gender = null;
  @SerializedName("Color")
  private String color = null;
  @SerializedName("Metadata")
  private String metadata = null;
  @SerializedName("Status")
  private Integer status = null;
  @SerializedName("Race")
  private String race = null;
  @SerializedName("AgeRange")
  private String ageRange = null;
  @SerializedName("ID")
  private String ID = null;

  /**
   **/
  @ApiModelProperty(value = "")
  public String getDisplayName() {
    return displayName;
  }
  public void setDisplayName(String displayName) {
    this.displayName = displayName;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public String getDescription() {
    return description;
  }
  public void setDescription(String description) {
    this.description = description;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public String getVirtualCurrency() {
    return virtualCurrency;
  }
  public void setVirtualCurrency(String virtualCurrency) {
    this.virtualCurrency = virtualCurrency;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public Integer getRealCurrency() {
    return realCurrency;
  }
  public void setRealCurrency(Integer realCurrency) {
    this.realCurrency = realCurrency;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public String getCustomMetaData() {
    return customMetaData;
  }
  public void setCustomMetaData(String customMetaData) {
    this.customMetaData = customMetaData;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public String getItemThumbnailsUrl() {
    return imageArtifacts;
  }
  public void setItemThumbnailsUrl(String imageArtifacts) {
    this.imageArtifacts = imageArtifacts;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public String getArtifacts() {
    return meshArtifacts;
  }
  public void setArtifacts(String artifacts) {
    this.meshArtifacts = artifacts;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public String getBlendshapeKeys() {
    return blendshapeKeys;
  }
  public void setBlendshapeKeys(String blendshapeKeys) {
    this.blendshapeKeys = blendshapeKeys;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public String getTags() {
    return tags;
  }
  public void setTags(String tags) {
    this.tags = tags;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public String getProps() {
    return props;
  }
  public void setProps(String props) {
    this.props = props;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public Integer getGender() {
    return gender;
  }
  public void setGender(Integer gender) {
    this.gender = gender;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public String getColor() {
    return color;
  }
  public void setColor(String color) {
    this.color = color;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public String getMetadata() {
    return metadata;
  }
  public void setMetadata(String metadata) {
    this.metadata = metadata;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public Integer getStatus() {
    return status;
  }
  public void setStatus(Integer status) {
    this.status = status;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public String getRace() {
    return race;
  }
  public void setRace(String race) {
    this.race = race;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public String getAgeRange() {
    return ageRange;
  }
  public void setAgeRange(String ageRange) {
    this.ageRange = ageRange;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public String getUserID() {
    return ID;
  }
  public void setUserID(String userID) {
    this.ID = userID;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    GetAvatarPresetByIDRequestData getAvatarPresetByIDRequestData = (GetAvatarPresetByIDRequestData) o;
    return (this.displayName == null ? getAvatarPresetByIDRequestData.displayName == null : this.displayName.equals(getAvatarPresetByIDRequestData.displayName)) &&
        (this.description == null ? getAvatarPresetByIDRequestData.description == null : this.description.equals(getAvatarPresetByIDRequestData.description)) &&
        (this.virtualCurrency == null ? getAvatarPresetByIDRequestData.virtualCurrency == null : this.virtualCurrency.equals(getAvatarPresetByIDRequestData.virtualCurrency)) &&
        (this.realCurrency == null ? getAvatarPresetByIDRequestData.realCurrency == null : this.realCurrency.equals(getAvatarPresetByIDRequestData.realCurrency)) &&
        (this.customMetaData == null ? getAvatarPresetByIDRequestData.customMetaData == null : this.customMetaData.equals(getAvatarPresetByIDRequestData.customMetaData)) &&
        (this.imageArtifacts == null ? getAvatarPresetByIDRequestData.imageArtifacts == null : this.imageArtifacts.equals(getAvatarPresetByIDRequestData.imageArtifacts)) &&
        (this.meshArtifacts == null ? getAvatarPresetByIDRequestData.meshArtifacts == null : this.meshArtifacts.equals(getAvatarPresetByIDRequestData.meshArtifacts)) &&
        (this.blendshapeKeys == null ? getAvatarPresetByIDRequestData.blendshapeKeys == null : this.blendshapeKeys.equals(getAvatarPresetByIDRequestData.blendshapeKeys)) &&
        (this.tags == null ? getAvatarPresetByIDRequestData.tags == null : this.tags.equals(getAvatarPresetByIDRequestData.tags)) &&
        (this.props == null ? getAvatarPresetByIDRequestData.props == null : this.props.equals(getAvatarPresetByIDRequestData.props)) &&
        (this.gender == null ? getAvatarPresetByIDRequestData.gender == null : this.gender.equals(getAvatarPresetByIDRequestData.gender)) &&
        (this.color == null ? getAvatarPresetByIDRequestData.color == null : this.color.equals(getAvatarPresetByIDRequestData.color)) &&
        (this.metadata == null ? getAvatarPresetByIDRequestData.metadata == null : this.metadata.equals(getAvatarPresetByIDRequestData.metadata)) &&
        (this.status == null ? getAvatarPresetByIDRequestData.status == null : this.status.equals(getAvatarPresetByIDRequestData.status)) &&
        (this.race == null ? getAvatarPresetByIDRequestData.race == null : this.race.equals(getAvatarPresetByIDRequestData.race)) &&
        (this.ageRange == null ? getAvatarPresetByIDRequestData.ageRange == null : this.ageRange.equals(getAvatarPresetByIDRequestData.ageRange)) &&
        (this.ID == null ? getAvatarPresetByIDRequestData.ID == null : this.ID.equals(getAvatarPresetByIDRequestData.ID));
  }

  @Override
  public int hashCode() {
    int result = 17;
    result = 31 * result + (this.displayName == null ? 0: this.displayName.hashCode());
    result = 31 * result + (this.description == null ? 0: this.description.hashCode());
    result = 31 * result + (this.virtualCurrency == null ? 0: this.virtualCurrency.hashCode());
    result = 31 * result + (this.realCurrency == null ? 0: this.realCurrency.hashCode());
    result = 31 * result + (this.customMetaData == null ? 0: this.customMetaData.hashCode());
    result = 31 * result + (this.imageArtifacts == null ? 0: this.imageArtifacts.hashCode());
    result = 31 * result + (this.meshArtifacts == null ? 0: this.meshArtifacts.hashCode());
    result = 31 * result + (this.blendshapeKeys == null ? 0: this.blendshapeKeys.hashCode());
    result = 31 * result + (this.tags == null ? 0: this.tags.hashCode());
    result = 31 * result + (this.props == null ? 0: this.props.hashCode());
    result = 31 * result + (this.gender == null ? 0: this.gender.hashCode());
    result = 31 * result + (this.color == null ? 0: this.color.hashCode());
    result = 31 * result + (this.metadata == null ? 0: this.metadata.hashCode());
    result = 31 * result + (this.status == null ? 0: this.status.hashCode());
    result = 31 * result + (this.race == null ? 0: this.race.hashCode());
    result = 31 * result + (this.ageRange == null ? 0: this.ageRange.hashCode());
    result = 31 * result + (this.ID == null ? 0: this.ID.hashCode());
    return result;
  }

  @Override
  public String toString()  {
    StringBuilder sb = new StringBuilder();
    sb.append("class GetAvatarPresetByIDRequestData {\n");
    
    sb.append("  displayName: ").append(displayName).append("\n");
    sb.append("  description: ").append(description).append("\n");
    sb.append("  virtualCurrency: ").append(virtualCurrency).append("\n");
    sb.append("  realCurrency: ").append(realCurrency).append("\n");
    sb.append("  customMetaData: ").append(customMetaData).append("\n");
    sb.append("  imageArtifacts: ").append(imageArtifacts).append("\n");
    sb.append("  meshArtifacts: ").append(meshArtifacts).append("\n");
    sb.append("  blendshapeKeys: ").append(blendshapeKeys).append("\n");
    sb.append("  tags: ").append(tags).append("\n");
    sb.append("  props: ").append(props).append("\n");
    sb.append("  gender: ").append(gender).append("\n");
    sb.append("  color: ").append(color).append("\n");
    sb.append("  metadata: ").append(metadata).append("\n");
    sb.append("  status: ").append(status).append("\n");
    sb.append("  race: ").append(race).append("\n");
    sb.append("  ageRange: ").append(ageRange).append("\n");
    sb.append("  ID: ").append(ID).append("\n");
    sb.append("}\n");
    return sb.toString();
  }
}
