/**
 * Client
 * AvatarYug Client side API
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package Avataryug.Client.Model;

import java.util.*;
//import org.openapitools.client.model.OasAnyTypeNotMapped;
import io.swagger.annotations.*;
import com.google.gson.annotations.SerializedName;

@ApiModel(description = "")
public class GetAdPlacementByIDResultDataRewardsInner {
  
  @SerializedName("ActionArray")
  private List<GetAdPlacementByIDResultDataRewardsInnerActionArrayInner> actionArray = null;
  @SerializedName("Checked")
  private Boolean checked = null;
//  @SerializedName("Description")
//  private OasAnyTypeNotMapped description = null;
  @SerializedName("ID")
  private Integer ID = null;
  @SerializedName("Name")
  private String name = null;
  @SerializedName("Odds")
  private String odds = null;
//  @SerializedName("RewardURL")
//  private OasAnyTypeNotMapped rewardURL = null;
  @SerializedName("Selected")
  private Boolean selected = null;
  @SerializedName("Value")
  private String value = null;

  /**
   **/
  @ApiModelProperty(required = true, value = "")
  public List<GetAdPlacementByIDResultDataRewardsInnerActionArrayInner> getActionArray() {
    return actionArray;
  }
  public void setActionArray(List<GetAdPlacementByIDResultDataRewardsInnerActionArrayInner> actionArray) {
    this.actionArray = actionArray;
  }

  /**
   **/
  @ApiModelProperty(required = true, value = "")
  public Boolean getChecked() {
    return checked;
  }
  public void setChecked(Boolean checked) {
    this.checked = checked;
  }

  /**
   **/
//  @ApiModelProperty(required = true, value = "")
//  public OasAnyTypeNotMapped getDescription() {
//    return description;
//  }
//  public void setDescription(OasAnyTypeNotMapped description) {
//    this.description = description;
//  }

  /**
   **/
  @ApiModelProperty(required = true, value = "")
  public Integer getID() {
    return ID;
  }
  public void setID(Integer ID) {
    this.ID = ID;
  }

  /**
   **/
  @ApiModelProperty(required = true, value = "")
  public String getName() {
    return name;
  }
  public void setName(String name) {
    this.name = name;
  }

  /**
   **/
  @ApiModelProperty(required = true, value = "")
  public String getOdds() {
    return odds;
  }
  public void setOdds(String odds) {
    this.odds = odds;
  }

  /**
   **/
//  @ApiModelProperty(required = true, value = "")
//  public OasAnyTypeNotMapped getRewardURL() {
//    return rewardURL;
//  }
//  public void setRewardURL(OasAnyTypeNotMapped rewardURL) {
//    this.rewardURL = rewardURL;
//  }

  /**
   **/
  @ApiModelProperty(required = true, value = "")
  public Boolean getSelected() {
    return selected;
  }
  public void setSelected(Boolean selected) {
    this.selected = selected;
  }

  /**
   **/
  @ApiModelProperty(required = true, value = "")
  public String getValue() {
    return value;
  }
  public void setValue(String value) {
    this.value = value;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    GetAdPlacementByIDResultDataRewardsInner getAdPlacementByIDResultDataRewardsInner = (GetAdPlacementByIDResultDataRewardsInner) o;
    return (this.actionArray == null ? getAdPlacementByIDResultDataRewardsInner.actionArray == null : this.actionArray.equals(getAdPlacementByIDResultDataRewardsInner.actionArray)) &&
        (this.checked == null ? getAdPlacementByIDResultDataRewardsInner.checked == null : this.checked.equals(getAdPlacementByIDResultDataRewardsInner.checked)) &&
//        (this.description == null ? getAdPlacementByIDResultDataRewardsInner.description == null : this.description.equals(getAdPlacementByIDResultDataRewardsInner.description)) &&
        (this.ID == null ? getAdPlacementByIDResultDataRewardsInner.ID == null : this.ID.equals(getAdPlacementByIDResultDataRewardsInner.ID)) &&
        (this.name == null ? getAdPlacementByIDResultDataRewardsInner.name == null : this.name.equals(getAdPlacementByIDResultDataRewardsInner.name)) &&
        (this.odds == null ? getAdPlacementByIDResultDataRewardsInner.odds == null : this.odds.equals(getAdPlacementByIDResultDataRewardsInner.odds)) &&
//        (this.rewardURL == null ? getAdPlacementByIDResultDataRewardsInner.rewardURL == null : this.rewardURL.equals(getAdPlacementByIDResultDataRewardsInner.rewardURL)) &&
        (this.selected == null ? getAdPlacementByIDResultDataRewardsInner.selected == null : this.selected.equals(getAdPlacementByIDResultDataRewardsInner.selected)) &&
        (this.value == null ? getAdPlacementByIDResultDataRewardsInner.value == null : this.value.equals(getAdPlacementByIDResultDataRewardsInner.value));
  }

  @Override
  public int hashCode() {
    int result = 17;
    result = 31 * result + (this.actionArray == null ? 0: this.actionArray.hashCode());
    result = 31 * result + (this.checked == null ? 0: this.checked.hashCode());
//    result = 31 * result + (this.description == null ? 0: this.description.hashCode());
    result = 31 * result + (this.ID == null ? 0: this.ID.hashCode());
    result = 31 * result + (this.name == null ? 0: this.name.hashCode());
    result = 31 * result + (this.odds == null ? 0: this.odds.hashCode());
//    result = 31 * result + (this.rewardURL == null ? 0: this.rewardURL.hashCode());
    result = 31 * result + (this.selected == null ? 0: this.selected.hashCode());
    result = 31 * result + (this.value == null ? 0: this.value.hashCode());
    return result;
  }

  @Override
  public String toString()  {
    StringBuilder sb = new StringBuilder();
    sb.append("class GetAdPlacementByIDResultDataRewardsInner {\n");
    
    sb.append("  actionArray: ").append(actionArray).append("\n");
    sb.append("  checked: ").append(checked).append("\n");
//    sb.append("  description: ").append(description).append("\n");
    sb.append("  ID: ").append(ID).append("\n");
    sb.append("  name: ").append(name).append("\n");
    sb.append("  odds: ").append(odds).append("\n");
//    sb.append("  rewardURL: ").append(rewardURL).append("\n");
    sb.append("  selected: ").append(selected).append("\n");
    sb.append("  value: ").append(value).append("\n");
    sb.append("}\n");
    return sb.toString();
  }
}
