/**
 * Client
 * AvatarYug Client side API
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package Avataryug.Client.Model;

import io.swagger.annotations.*;
import com.google.gson.annotations.SerializedName;

import java.util.List;

@ApiModel(description = "")
public class GetClipsResultDataInner {
  
  @SerializedName("DisplayName")
  private String displayName = null;
  @SerializedName("Description")
  private String description = null;
  @SerializedName("Category")
  private String category = null;
  @SerializedName("CustomMetaData")
  private String customMetaData = null;
  @SerializedName("ThumbnailUrl")
  private List<ClipThumbnails> ThumbnailUrl = null;
//  @SerializedName("Artifacts")
//  private List artifacts = null;
  @SerializedName("Tags")
  private String tags = null;
  @SerializedName("Color")
  private String color = null;
  @SerializedName("Metadata")
  private String metadata = null;
  @SerializedName("Status")
  private Integer status = null;
  @SerializedName("ClipType")
  private Integer clipType = null;
  @SerializedName("ID")
  private String ID = null;

  @SerializedName("ClipTemplateID")
  private String ClipTemplateID = null;

  /**
   **/
  @ApiModelProperty(required = true, value = "")
  public String getDisplayName() {
    return displayName;
  }
  public void setDisplayName(String displayName) {
    this.displayName = displayName;
  }

  /**
   **/
  @ApiModelProperty(required = true, value = "")
  public String getDescription() {
    return description;
  }
  public void setDescription(String description) {
    this.description = description;
  }

  /**
   **/
  @ApiModelProperty(required = true, value = "")
  public String getCategory() {
    return category;
  }
  public void setCategory(String category) {
    this.category = category;
  }

  /**
   **/
  @ApiModelProperty(required = true, value = "")
  public String getCustomMetaData() {
    return customMetaData;
  }
  public void setCustomMetaData(String customMetaData) {
    this.customMetaData = customMetaData;
  }

  /**
   **/
  @ApiModelProperty(required = true, value = "")
  public List<ClipThumbnails> getThumbnailsUrl() {
    return ThumbnailUrl;
  }
  public void setThumbnailsUrl(List<ClipThumbnails> thumbnailsUrl) {
    this.ThumbnailUrl = thumbnailsUrl;
  }

  /**
   **/
//  @ApiModelProperty(required = true, value = "")
//  public List getArtifacts() {
//    return artifacts;
//  }
//  public void setArtifacts(List artifacts) {
//    this.artifacts = artifacts;
//  }

  /**
   **/
  @ApiModelProperty(required = true, value = "")
  public String getTags() {
    return tags;
  }
  public void setTags(String tags) {
    this.tags = tags;
  }

  /**
   **/
  @ApiModelProperty(required = true, value = "")
  public String getColor() {
    return color;
  }
  public void setColor(String color) {
    this.color = color;
  }

  /**
   **/
  @ApiModelProperty(required = true, value = "")
  public String getMetadata() {
    return metadata;
  }
  public void setMetadata(String metadata) {
    this.metadata = metadata;
  }

  /**
   **/
  @ApiModelProperty(required = true, value = "")
  public Integer getStatus() {
    return status;
  }
  public void setStatus(Integer status) {
    this.status = status;
  }

  /**
   **/
  @ApiModelProperty(required = true, value = "")
  public Integer getClipType() {
    return clipType;
  }
  public void setClipType(Integer clipType) {
    this.clipType = clipType;
  }

  /**
   **/
  @ApiModelProperty(required = true, value = "")
  public String getID() {
    return ID;
  }
  public void setID(String ID) {
    this.ID = ID;
  }

  @ApiModelProperty(required = true, value = "")
  public String getClipTemplateID() {
    return ClipTemplateID;
  }
  public void setClipTemplateID(String ID) {
    this.ClipTemplateID = ClipTemplateID;
  }

  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    GetClipsResultDataInner getClipsResultDataInner = (GetClipsResultDataInner) o;
    return (this.displayName == null ? getClipsResultDataInner.displayName == null : this.displayName.equals(getClipsResultDataInner.displayName)) &&
        (this.description == null ? getClipsResultDataInner.description == null : this.description.equals(getClipsResultDataInner.description)) &&
        (this.category == null ? getClipsResultDataInner.category == null : this.category.equals(getClipsResultDataInner.category)) &&
        (this.customMetaData == null ? getClipsResultDataInner.customMetaData == null : this.customMetaData.equals(getClipsResultDataInner.customMetaData)) &&
        (this.ThumbnailUrl == null ? getClipsResultDataInner.ThumbnailUrl == null : this.ThumbnailUrl.equals(getClipsResultDataInner.ThumbnailUrl)) &&
//        (this.artifacts == null ? getClipsResultDataInner.artifacts == null : this.artifacts.equals(getClipsResultDataInner.artifacts)) &&
        (this.tags == null ? getClipsResultDataInner.tags == null : this.tags.equals(getClipsResultDataInner.tags)) &&
        (this.color == null ? getClipsResultDataInner.color == null : this.color.equals(getClipsResultDataInner.color)) &&
        (this.metadata == null ? getClipsResultDataInner.metadata == null : this.metadata.equals(getClipsResultDataInner.metadata)) &&
        (this.status == null ? getClipsResultDataInner.status == null : this.status.equals(getClipsResultDataInner.status)) &&
        (this.clipType == null ? getClipsResultDataInner.clipType == null : this.clipType.equals(getClipsResultDataInner.clipType)) &&
        (this.ID == null ? getClipsResultDataInner.ID == null : this.ID.equals(getClipsResultDataInner.ID)) &&
            (this.ClipTemplateID == null ? getClipsResultDataInner.ClipTemplateID == null : this.ClipTemplateID.equals(getClipsResultDataInner.ClipTemplateID)) ;
  }

  @Override
  public int hashCode() {
    int result = 17;
    result = 31 * result + (this.displayName == null ? 0: this.displayName.hashCode());
    result = 31 * result + (this.description == null ? 0: this.description.hashCode());
    result = 31 * result + (this.category == null ? 0: this.category.hashCode());
    result = 31 * result + (this.customMetaData == null ? 0: this.customMetaData.hashCode());
    result = 31 * result + (this.ThumbnailUrl == null ? 0: this.ThumbnailUrl.hashCode());
//    result = 31 * result + (this.artifacts == null ? 0: this.artifacts.hashCode());
    result = 31 * result + (this.tags == null ? 0: this.tags.hashCode());
    result = 31 * result + (this.color == null ? 0: this.color.hashCode());
    result = 31 * result + (this.metadata == null ? 0: this.metadata.hashCode());
    result = 31 * result + (this.status == null ? 0: this.status.hashCode());
    result = 31 * result + (this.clipType == null ? 0: this.clipType.hashCode());
    result = 31 * result + (this.ID == null ? 0: this.ID.hashCode());
    result = 31 * result + (this.ClipTemplateID == null ? 0: this.ClipTemplateID.hashCode());
    return result;
  }

  @Override
  public String toString()  {
    StringBuilder sb = new StringBuilder();
    sb.append("class GetClipsResultDataInner {\n");
    
    sb.append("  displayName: ").append(displayName).append("\n");
    sb.append("  description: ").append(description).append("\n");
    sb.append("  category: ").append(category).append("\n");
    sb.append("  customMetaData: ").append(customMetaData).append("\n");
    sb.append("  ThumbnailUrl: ").append(ThumbnailUrl).append("\n");
//    sb.append("  artifacts: ").append(artifacts).append("\n");
    sb.append("  tags: ").append(tags).append("\n");
    sb.append("  color: ").append(color).append("\n");
    sb.append("  metadata: ").append(metadata).append("\n");
    sb.append("  status: ").append(status).append("\n");
    sb.append("  clipType: ").append(clipType).append("\n");
    sb.append("  ID: ").append(ID).append("\n");
    sb.append("  ClipTemplateID: ").append(ClipTemplateID).append("\n");
    sb.append("}\n");
    return sb.toString();
  }
}
