/**
 * Client
 * AvatarYug Client side API
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package Avataryug.Client.Model;

import io.swagger.annotations.*;
import com.google.gson.annotations.SerializedName;

@ApiModel(description = "")
public class GetClipsByIDResultDataCustomMetaDataInner {
  
  @SerializedName("key")
  private String key = null;
  @SerializedName("selected")
  private Boolean selected = null;
  @SerializedName("value")
  private String value = null;

  /**
   **/
  @ApiModelProperty(required = true, value = "")
  public String getKey() {
    return key;
  }
  public void setKey(String key) {
    this.key = key;
  }

  /**
   **/
  @ApiModelProperty(required = true, value = "")
  public Boolean getSelected() {
    return selected;
  }
  public void setSelected(Boolean selected) {
    this.selected = selected;
  }

  /**
   **/
  @ApiModelProperty(required = true, value = "")
  public String getValue() {
    return value;
  }
  public void setValue(String value) {
    this.value = value;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    GetClipsByIDResultDataCustomMetaDataInner getClipsByIDResultDataCustomMetaDataInner = (GetClipsByIDResultDataCustomMetaDataInner) o;
    return (this.key == null ? getClipsByIDResultDataCustomMetaDataInner.key == null : this.key.equals(getClipsByIDResultDataCustomMetaDataInner.key)) &&
        (this.selected == null ? getClipsByIDResultDataCustomMetaDataInner.selected == null : this.selected.equals(getClipsByIDResultDataCustomMetaDataInner.selected)) &&
        (this.value == null ? getClipsByIDResultDataCustomMetaDataInner.value == null : this.value.equals(getClipsByIDResultDataCustomMetaDataInner.value));
  }

  @Override
  public int hashCode() {
    int result = 17;
    result = 31 * result + (this.key == null ? 0: this.key.hashCode());
    result = 31 * result + (this.selected == null ? 0: this.selected.hashCode());
    result = 31 * result + (this.value == null ? 0: this.value.hashCode());
    return result;
  }

  @Override
  public String toString()  {
    StringBuilder sb = new StringBuilder();
    sb.append("class GetClipsByIDResultDataCustomMetaDataInner {\n");
    
    sb.append("  key: ").append(key).append("\n");
    sb.append("  selected: ").append(selected).append("\n");
    sb.append("  value: ").append(value).append("\n");
    sb.append("}\n");
    return sb.toString();
  }
}
