/**
 * Client
 * AvatarYug Client side API
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package Avataryug.Client.Model;

import io.swagger.annotations.*;
import com.google.gson.annotations.SerializedName;

@ApiModel(description = "")
public class PayForPurchaseRequest {
  
  @SerializedName("UserID")
  private String userID = null;
  @SerializedName("TransactionID")
  private String transactionID = null;
  @SerializedName("PaymentProvider")
  private String paymentProvider = null;
  @SerializedName("Metadata")
  private String metadata = null;
  @SerializedName("CurrencyCode")
  private String currencyCode = null;

  /**
   **/
  @ApiModelProperty(value = "")
  public String getUserID() {
    return userID;
  }
  public void setUserID(String userID) {
    this.userID = userID;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public String getTransactionID() {
    return transactionID;
  }
  public void setTransactionID(String transactionID) {
    this.transactionID = transactionID;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public String getPaymentProvider() {
    return paymentProvider;
  }
  public void setPaymentProvider(String paymentProvider) {
    this.paymentProvider = paymentProvider;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public String getMetadata() {
    return metadata;
  }
  public void setMetadata(String metadata) {
    this.metadata = metadata;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public String getCurrencyCode() {
    return currencyCode;
  }
  public void setCurrencyCode(String currencyCode) {
    this.currencyCode = currencyCode;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    PayForPurchaseRequest payForPurchaseRequest = (PayForPurchaseRequest) o;
    return (this.userID == null ? payForPurchaseRequest.userID == null : this.userID.equals(payForPurchaseRequest.userID)) &&
        (this.transactionID == null ? payForPurchaseRequest.transactionID == null : this.transactionID.equals(payForPurchaseRequest.transactionID)) &&
        (this.paymentProvider == null ? payForPurchaseRequest.paymentProvider == null : this.paymentProvider.equals(payForPurchaseRequest.paymentProvider)) &&
        (this.metadata == null ? payForPurchaseRequest.metadata == null : this.metadata.equals(payForPurchaseRequest.metadata)) &&
        (this.currencyCode == null ? payForPurchaseRequest.currencyCode == null : this.currencyCode.equals(payForPurchaseRequest.currencyCode));
  }

  @Override
  public int hashCode() {
    int result = 17;
    result = 31 * result + (this.userID == null ? 0: this.userID.hashCode());
    result = 31 * result + (this.transactionID == null ? 0: this.transactionID.hashCode());
    result = 31 * result + (this.paymentProvider == null ? 0: this.paymentProvider.hashCode());
    result = 31 * result + (this.metadata == null ? 0: this.metadata.hashCode());
    result = 31 * result + (this.currencyCode == null ? 0: this.currencyCode.hashCode());
    return result;
  }

  @Override
  public String toString()  {
    StringBuilder sb = new StringBuilder();
    sb.append("class PayForPurchaseRequest {\n");
    
    sb.append("  userID: ").append(userID).append("\n");
    sb.append("  transactionID: ").append(transactionID).append("\n");
    sb.append("  paymentProvider: ").append(paymentProvider).append("\n");
    sb.append("  metadata: ").append(metadata).append("\n");
    sb.append("  currencyCode: ").append(currencyCode).append("\n");
    sb.append("}\n");
    return sb.toString();
  }
}
