/**
 * Client
 * AvatarYug Client side API
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package Avataryug.Client.Model;

import io.swagger.annotations.*;
import com.google.gson.annotations.SerializedName;

@ApiModel(description = "")
public class SubtractUserVirtualCurrencyRequest {
  
  @SerializedName("VirtualCurrency")
  private String virtualCurrency = null;
  @SerializedName("Amount")
  private Integer amount = null;

  /**
   * Name of the virtual currency which is to be decremented.
   **/
  @ApiModelProperty(required = true, value = "Name of the virtual currency which is to be decremented.")
  public String getVirtualCurrency() {
    return virtualCurrency;
  }
  public void setVirtualCurrency(String virtualCurrency) {
    this.virtualCurrency = virtualCurrency;
  }

  /**
   * Amount to be subtracted from the user balance of the specified virtual currency.
   **/
  @ApiModelProperty(required = true, value = "Amount to be subtracted from the user balance of the specified virtual currency.")
  public Integer getAmount() {
    return amount;
  }
  public void setAmount(Integer amount) {
    this.amount = amount;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    SubtractUserVirtualCurrencyRequest subtractUserVirtualCurrencyRequest = (SubtractUserVirtualCurrencyRequest) o;
    return (this.virtualCurrency == null ? subtractUserVirtualCurrencyRequest.virtualCurrency == null : this.virtualCurrency.equals(subtractUserVirtualCurrencyRequest.virtualCurrency)) &&
        (this.amount == null ? subtractUserVirtualCurrencyRequest.amount == null : this.amount.equals(subtractUserVirtualCurrencyRequest.amount));
  }

  @Override
  public int hashCode() {
    int result = 17;
    result = 31 * result + (this.virtualCurrency == null ? 0: this.virtualCurrency.hashCode());
    result = 31 * result + (this.amount == null ? 0: this.amount.hashCode());
    return result;
  }

  @Override
  public String toString()  {
    StringBuilder sb = new StringBuilder();
    sb.append("class SubtractUserVirtualCurrencyRequest {\n");
    
    sb.append("  virtualCurrency: ").append(virtualCurrency).append("\n");
    sb.append("  amount: ").append(amount).append("\n");
    sb.append("}\n");
    return sb.toString();
  }
}
