/**
 * Client
 * AvatarYug Client side API
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package org.openapitools.client.model;

import io.swagger.annotations.*;
import com.google.gson.annotations.SerializedName;

@ApiModel(description = "")
public class GenerateAvatarMeshRequest {
  
  @SerializedName("AvatarID")
  private String avatarID = null;
  @SerializedName("Platform")
  private String platform = null;

  /**
   * Unique identifier for the generated avatar
   **/
  @ApiModelProperty(required = true, value = "Unique identifier for the generated avatar")
  public String getAvatarID() {
    return avatarID;
  }
  public void setAvatarID(String avatarID) {
    this.avatarID = avatarID;
  }

  /**
   * Name of the platform i.e. Android, IOS
   **/
  @ApiModelProperty(required = true, value = "Name of the platform i.e. Android, IOS")
  public String getPlatform() {
    return platform;
  }
  public void setPlatform(String platform) {
    this.platform = platform;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    GenerateAvatarMeshRequest generateAvatarMeshRequest = (GenerateAvatarMeshRequest) o;
    return (this.avatarID == null ? generateAvatarMeshRequest.avatarID == null : this.avatarID.equals(generateAvatarMeshRequest.avatarID)) &&
        (this.platform == null ? generateAvatarMeshRequest.platform == null : this.platform.equals(generateAvatarMeshRequest.platform));
  }

  @Override
  public int hashCode() {
    int result = 17;
    result = 31 * result + (this.avatarID == null ? 0: this.avatarID.hashCode());
    result = 31 * result + (this.platform == null ? 0: this.platform.hashCode());
    return result;
  }

  @Override
  public String toString()  {
    StringBuilder sb = new StringBuilder();
    sb.append("class GenerateAvatarMeshRequest {\n");
    
    sb.append("  avatarID: ").append(avatarID).append("\n");
    sb.append("  platform: ").append(platform).append("\n");
    sb.append("}\n");
    return sb.toString();
  }
}
