/**
 * Client
 * AvatarYug Client side API
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package org.openapitools.client.model;

import io.swagger.annotations.*;
import com.google.gson.annotations.SerializedName;

@ApiModel(description = "")
public class GenerateAvatarMeshResultData {
  
  @SerializedName("Platform")
  private String platform = null;
  @SerializedName("MeshURL")
  private String meshURL = null;

  /**
   **/
  @ApiModelProperty(value = "")
  public String getPlatform() {
    return platform;
  }
  public void setPlatform(String platform) {
    this.platform = platform;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public String getMeshURL() {
    return meshURL;
  }
  public void setMeshURL(String meshURL) {
    this.meshURL = meshURL;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    GenerateAvatarMeshResultData generateAvatarMeshResultData = (GenerateAvatarMeshResultData) o;
    return (this.platform == null ? generateAvatarMeshResultData.platform == null : this.platform.equals(generateAvatarMeshResultData.platform)) &&
        (this.meshURL == null ? generateAvatarMeshResultData.meshURL == null : this.meshURL.equals(generateAvatarMeshResultData.meshURL));
  }

  @Override
  public int hashCode() {
    int result = 17;
    result = 31 * result + (this.platform == null ? 0: this.platform.hashCode());
    result = 31 * result + (this.meshURL == null ? 0: this.meshURL.hashCode());
    return result;
  }

  @Override
  public String toString()  {
    StringBuilder sb = new StringBuilder();
    sb.append("class GenerateAvatarMeshResultData {\n");
    
    sb.append("  platform: ").append(platform).append("\n");
    sb.append("  meshURL: ").append(meshURL).append("\n");
    sb.append("}\n");
    return sb.toString();
  }
}
