/**
 * Client
 * AvatarYug Client side API
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package org.openapitools.client.model;

import java.util.*;
import org.openapitools.client.model.GrantInstanceToUserRequestInstanceIDsInner;
import io.swagger.annotations.*;
import com.google.gson.annotations.SerializedName;

@ApiModel(description = "")
public class GrantInstanceToUserRequest {
  
  @SerializedName("InstanceIDs")
  private List<GrantInstanceToUserRequestInstanceIDsInner> instanceIDs = null;

  /**
   **/
  @ApiModelProperty(value = "")
  public List<GrantInstanceToUserRequestInstanceIDsInner> getInstanceIDs() {
    return instanceIDs;
  }
  public void setInstanceIDs(List<GrantInstanceToUserRequestInstanceIDsInner> instanceIDs) {
    this.instanceIDs = instanceIDs;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    GrantInstanceToUserRequest grantInstanceToUserRequest = (GrantInstanceToUserRequest) o;
    return (this.instanceIDs == null ? grantInstanceToUserRequest.instanceIDs == null : this.instanceIDs.equals(grantInstanceToUserRequest.instanceIDs));
  }

  @Override
  public int hashCode() {
    int result = 17;
    result = 31 * result + (this.instanceIDs == null ? 0: this.instanceIDs.hashCode());
    return result;
  }

  @Override
  public String toString()  {
    StringBuilder sb = new StringBuilder();
    sb.append("class GrantInstanceToUserRequest {\n");
    
    sb.append("  instanceIDs: ").append(instanceIDs).append("\n");
    sb.append("}\n");
    return sb.toString();
  }
}
