/**
 * Client
 * AvatarYug Client side API
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package org.openapitools.client.model;

import io.swagger.annotations.*;
import com.google.gson.annotations.SerializedName;

@ApiModel(description = "")
public class GrantAvatarPresetItemsToUserRequestItemIDsInner {
  
  @SerializedName("ItemID")
  private String itemID = null;

  /**
   * Unique idenifier of the item being granted
   **/
  @ApiModelProperty(required = true, value = "Unique idenifier of the item being granted")
  public String getItemID() {
    return itemID;
  }
  public void setItemID(String itemID) {
    this.itemID = itemID;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    GrantAvatarPresetItemsToUserRequestItemIDsInner grantAvatarPresetItemsToUserRequestItemIDsInner = (GrantAvatarPresetItemsToUserRequestItemIDsInner) o;
    return (this.itemID == null ? grantAvatarPresetItemsToUserRequestItemIDsInner.itemID == null : this.itemID.equals(grantAvatarPresetItemsToUserRequestItemIDsInner.itemID));
  }

  @Override
  public int hashCode() {
    int result = 17;
    result = 31 * result + (this.itemID == null ? 0: this.itemID.hashCode());
    return result;
  }

  @Override
  public String toString()  {
    StringBuilder sb = new StringBuilder();
    sb.append("class GrantAvatarPresetItemsToUserRequestItemIDsInner {\n");
    
    sb.append("  itemID: ").append(itemID).append("\n");
    sb.append("}\n");
    return sb.toString();
  }
}
