/**
 * Client
 * AvatarYug Client side API
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package org.openapitools.client.model;

import io.swagger.annotations.*;
import com.google.gson.annotations.SerializedName;

@ApiModel(description = "")
public class LinkAndroidDeviceIDRequest {
  
  @SerializedName("ForceLink")
  private Boolean forceLink = null;
  @SerializedName("AndroidDeviceID")
  private String androidDeviceID = null;

  /**
   * If another user is already linked to the device, unlink the other user and re-link.
   **/
  @ApiModelProperty(value = "If another user is already linked to the device, unlink the other user and re-link.")
  public Boolean getForceLink() {
    return forceLink;
  }
  public void setForceLink(Boolean forceLink) {
    this.forceLink = forceLink;
  }

  /**
   * Android device identifier for the user's device.
   **/
  @ApiModelProperty(required = true, value = "Android device identifier for the user's device.")
  public String getAndroidDeviceID() {
    return androidDeviceID;
  }
  public void setAndroidDeviceID(String androidDeviceID) {
    this.androidDeviceID = androidDeviceID;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    LinkAndroidDeviceIDRequest linkAndroidDeviceIDRequest = (LinkAndroidDeviceIDRequest) o;
    return (this.forceLink == null ? linkAndroidDeviceIDRequest.forceLink == null : this.forceLink.equals(linkAndroidDeviceIDRequest.forceLink)) &&
        (this.androidDeviceID == null ? linkAndroidDeviceIDRequest.androidDeviceID == null : this.androidDeviceID.equals(linkAndroidDeviceIDRequest.androidDeviceID));
  }

  @Override
  public int hashCode() {
    int result = 17;
    result = 31 * result + (this.forceLink == null ? 0: this.forceLink.hashCode());
    result = 31 * result + (this.androidDeviceID == null ? 0: this.androidDeviceID.hashCode());
    return result;
  }

  @Override
  public String toString()  {
    StringBuilder sb = new StringBuilder();
    sb.append("class LinkAndroidDeviceIDRequest {\n");
    
    sb.append("  forceLink: ").append(forceLink).append("\n");
    sb.append("  androidDeviceID: ").append(androidDeviceID).append("\n");
    sb.append("}\n");
    return sb.toString();
  }
}
