/**
 * Client
 * AvatarYug Client side API
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package org.openapitools.client.model;

import io.swagger.annotations.*;
import com.google.gson.annotations.SerializedName;

@ApiModel(description = "")
public class LinkIOSDeviceIDRequest {
  
  @SerializedName("ForceLink")
  private Boolean forceLink = null;
  @SerializedName("DeviceID")
  private String deviceID = null;

  /**
   * If another user is already linked to the device, unlink the other user and re-link.
   **/
  @ApiModelProperty(value = "If another user is already linked to the device, unlink the other user and re-link.")
  public Boolean getForceLink() {
    return forceLink;
  }
  public void setForceLink(Boolean forceLink) {
    this.forceLink = forceLink;
  }

  /**
   *  iOS identifier for the user's device.
   **/
  @ApiModelProperty(required = true, value = " iOS identifier for the user's device.")
  public String getDeviceID() {
    return deviceID;
  }
  public void setDeviceID(String deviceID) {
    this.deviceID = deviceID;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    LinkIOSDeviceIDRequest linkIOSDeviceIDRequest = (LinkIOSDeviceIDRequest) o;
    return (this.forceLink == null ? linkIOSDeviceIDRequest.forceLink == null : this.forceLink.equals(linkIOSDeviceIDRequest.forceLink)) &&
        (this.deviceID == null ? linkIOSDeviceIDRequest.deviceID == null : this.deviceID.equals(linkIOSDeviceIDRequest.deviceID));
  }

  @Override
  public int hashCode() {
    int result = 17;
    result = 31 * result + (this.forceLink == null ? 0: this.forceLink.hashCode());
    result = 31 * result + (this.deviceID == null ? 0: this.deviceID.hashCode());
    return result;
  }

  @Override
  public String toString()  {
    StringBuilder sb = new StringBuilder();
    sb.append("class LinkIOSDeviceIDRequest {\n");
    
    sb.append("  forceLink: ").append(forceLink).append("\n");
    sb.append("  deviceID: ").append(deviceID).append("\n");
    sb.append("}\n");
    return sb.toString();
  }
}
