/**
 * Client
 * AvatarYug Client side API
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package org.openapitools.client.model;

import io.swagger.annotations.*;
import com.google.gson.annotations.SerializedName;

@ApiModel(description = "")
public class LoginWithFacebookRequest {
  
  @SerializedName("FacebookID")
  private String facebookID = null;
  @SerializedName("FbAccessToken")
  private String fbAccessToken = null;
  @SerializedName("CreateAccount")
  private Boolean createAccount = null;

  /**
   * Identifier provided by Facebook for this users FacebookID.
   **/
  @ApiModelProperty(required = true, value = "Identifier provided by Facebook for this users FacebookID.")
  public String getFacebookID() {
    return facebookID;
  }
  public void setFacebookID(String facebookID) {
    this.facebookID = facebookID;
  }

  /**
   * Unique identifier from Facebook for the user.
   **/
  @ApiModelProperty(required = true, value = "Unique identifier from Facebook for the user.")
  public String getFbAccessToken() {
    return fbAccessToken;
  }
  public void setFbAccessToken(String fbAccessToken) {
    this.fbAccessToken = fbAccessToken;
  }

  /**
   * Automatically create a AvatarYug account if one is not currently linked to this ID.
   **/
  @ApiModelProperty(value = "Automatically create a AvatarYug account if one is not currently linked to this ID.")
  public Boolean getCreateAccount() {
    return createAccount;
  }
  public void setCreateAccount(Boolean createAccount) {
    this.createAccount = createAccount;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    LoginWithFacebookRequest loginWithFacebookRequest = (LoginWithFacebookRequest) o;
    return (this.facebookID == null ? loginWithFacebookRequest.facebookID == null : this.facebookID.equals(loginWithFacebookRequest.facebookID)) &&
        (this.fbAccessToken == null ? loginWithFacebookRequest.fbAccessToken == null : this.fbAccessToken.equals(loginWithFacebookRequest.fbAccessToken)) &&
        (this.createAccount == null ? loginWithFacebookRequest.createAccount == null : this.createAccount.equals(loginWithFacebookRequest.createAccount));
  }

  @Override
  public int hashCode() {
    int result = 17;
    result = 31 * result + (this.facebookID == null ? 0: this.facebookID.hashCode());
    result = 31 * result + (this.fbAccessToken == null ? 0: this.fbAccessToken.hashCode());
    result = 31 * result + (this.createAccount == null ? 0: this.createAccount.hashCode());
    return result;
  }

  @Override
  public String toString()  {
    StringBuilder sb = new StringBuilder();
    sb.append("class LoginWithFacebookRequest {\n");
    
    sb.append("  facebookID: ").append(facebookID).append("\n");
    sb.append("  fbAccessToken: ").append(fbAccessToken).append("\n");
    sb.append("  createAccount: ").append(createAccount).append("\n");
    sb.append("}\n");
    return sb.toString();
  }
}
