/**
 * Client
 * AvatarYug Client side API
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package org.openapitools.client.model;

import io.swagger.annotations.*;
import com.google.gson.annotations.SerializedName;

@ApiModel(description = "")
public class UnlockContainerInstanceRequest {
  
  @SerializedName("ContainerInstanceID")
  private String containerInstanceID = null;
  @SerializedName("KeyInstanceID")
  private String keyInstanceID = null;

  /**
   * ItemInstanceId of the container to unlock.
   **/
  @ApiModelProperty(required = true, value = "ItemInstanceId of the container to unlock.")
  public String getContainerInstanceID() {
    return containerInstanceID;
  }
  public void setContainerInstanceID(String containerInstanceID) {
    this.containerInstanceID = containerInstanceID;
  }

  /**
   * ItemInstanceId of the key that will be consumed by unlocking this container. If the container requires a key, this parameter is required.
   **/
  @ApiModelProperty(required = true, value = "ItemInstanceId of the key that will be consumed by unlocking this container. If the container requires a key, this parameter is required.")
  public String getKeyInstanceID() {
    return keyInstanceID;
  }
  public void setKeyInstanceID(String keyInstanceID) {
    this.keyInstanceID = keyInstanceID;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    UnlockContainerInstanceRequest unlockContainerInstanceRequest = (UnlockContainerInstanceRequest) o;
    return (this.containerInstanceID == null ? unlockContainerInstanceRequest.containerInstanceID == null : this.containerInstanceID.equals(unlockContainerInstanceRequest.containerInstanceID)) &&
        (this.keyInstanceID == null ? unlockContainerInstanceRequest.keyInstanceID == null : this.keyInstanceID.equals(unlockContainerInstanceRequest.keyInstanceID));
  }

  @Override
  public int hashCode() {
    int result = 17;
    result = 31 * result + (this.containerInstanceID == null ? 0: this.containerInstanceID.hashCode());
    result = 31 * result + (this.keyInstanceID == null ? 0: this.keyInstanceID.hashCode());
    return result;
  }

  @Override
  public String toString()  {
    StringBuilder sb = new StringBuilder();
    sb.append("class UnlockContainerInstanceRequest {\n");
    
    sb.append("  containerInstanceID: ").append(containerInstanceID).append("\n");
    sb.append("  keyInstanceID: ").append(keyInstanceID).append("\n");
    sb.append("}\n");
    return sb.toString();
  }
}
