/**
 * Client
 * AvatarYug Client side API
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package org.openapitools.client.model;

import io.swagger.annotations.*;
import com.google.gson.annotations.SerializedName;

@ApiModel(description = "")
public class UpdateDefaultAvatarIDRequest {
  
  @SerializedName("DefaultAvatarID")
  private String defaultAvatarID = null;

  /**
   * Avatar ID of which needs to be set as Default
   **/
  @ApiModelProperty(required = true, value = "Avatar ID of which needs to be set as Default")
  public String getDefaultAvatarID() {
    return defaultAvatarID;
  }
  public void setDefaultAvatarID(String defaultAvatarID) {
    this.defaultAvatarID = defaultAvatarID;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    UpdateDefaultAvatarIDRequest updateDefaultAvatarIDRequest = (UpdateDefaultAvatarIDRequest) o;
    return (this.defaultAvatarID == null ? updateDefaultAvatarIDRequest.defaultAvatarID == null : this.defaultAvatarID.equals(updateDefaultAvatarIDRequest.defaultAvatarID));
  }

  @Override
  public int hashCode() {
    int result = 17;
    result = 31 * result + (this.defaultAvatarID == null ? 0: this.defaultAvatarID.hashCode());
    return result;
  }

  @Override
  public String toString()  {
    StringBuilder sb = new StringBuilder();
    sb.append("class UpdateDefaultAvatarIDRequest {\n");
    
    sb.append("  defaultAvatarID: ").append(defaultAvatarID).append("\n");
    sb.append("}\n");
    return sb.toString();
  }
}
